CONTRIBUTING.md, OWNERS, OWNERS_ALIASES, SECURITY.md, SECURITY_CONTACTS, code-of-conduct.md
=> Add required files for repository donation

github/internal/retry.go, github/internal/retry_test.go
We now check for the `github.RateLimitError` and use its result to wait
before an actual retry. This should avoid hitting the secondary rate
limit, as described there:
- https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
- https://docs.github.com/en/rest/guides/best-practices-for-integrators
Refers to https://github.com/kubernetes/release/issues/2225
=> Add support for GitHub rate limit error

test/integration/sign_test.go
This PR adds the integration tests for the `SignFile` function. The test is currently no-op because there's no implementation for `SignFile` (will be implemented in #29).
/assign @palnabarun @puerco @saschagrunert @cpanato 
=> Add the integration tests for SignFile

go.mod, go.sum, sign/impl.go, sign/options.go, sign/sign.go, sign/sign_test.go, sign/signfakes/fake_impl.go, test/integration/sign_test.go
=> Implement Image Signing Verification

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/record.go, github/replay.go
- introduce the update issue that will be needed for this feature in this PR: https://github.com/kubernetes/release/pull/1994
/assign @saschagrunert @puerco @Verolop @xmudrii @palnabarun 
=> github: add update issue api

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/record.go, github/replay.go
- introduce the add labels to issues that will be needed for this feature in this PR: https://github.com/kubernetes/release/pull/1994
/assign @saschagrunert @puerco @Verolop @xmudrii @palnabarun 
=> github: add labels to issues function

go.mod, go.sum
/kind cleanup
Update the dependencies to fix security related issues.
None
None
```release-note
None
```
=> Bump docker-distribution and image-spec deps

.github/dependabot.yml, github/github.go, github/record.go, github/replay.go, magefile.go, object/gcs.go, sign/impl.go
/kind cleanup
We should use dependabot in the same way for this repo as we do it for others.
None
None
```release-note
None
```
=> Add dependabot config file

go.mod
/kind failing-test
This should make dependabot updates work on this repository.
None
None
```release-note
Switched to go 1.18 modules as minimum requirement.
```
=> Switch to go 1.18

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum
/kind cleanup
Update go-github to its latest release.
None
None
```release-note
None
```
=> Update `go-github` to v45

go.mod, go.sum
/kind cleanup
Pin both dependencies to their latest release.
None
None
```release-note
None
```
=> Pin `go-containerregistry` and `release-utils`

git/git.go, go.mod, go.sum, test/integration/git_test.go
/kind cleanup
Switching to the latest go module compatible version.
None
```release-note
None
```
=> Switch to `github.com/blang/semver/v4`

.golangci.yml, git/git.go, git/git_test.go, github/github.go, github/internal/retry.go, magefile.go, object/gcs.go, object/store.go, regex/regex.go, sign/impl.go, sign/sign_test.go, test/integration/git_test.go
/kind cleanup
Update the config and fix some reported lints.
None
None
```release-note
None
```
=> Update golangci-lint and config

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum
/kind cleanup
- update go-github to version v47
/assign @saschagrunert @puerco @Verolop @xmudrii 
None
```release-note
NONE
```
=> update go-github to version v47

sign/sign.go
/kind feature
Adds an API to sign images by using custom options.
None
None
```release-note
None
```
=> Add sign.SignImageWithOptions() API

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum
/kind cleanup
- update go-github to v50
/assign @jeremyrickard @xmudrii @palnabarun @saschagrunert 
None
```release-note
NONE
```
=> update go-github to v50

go.mod, go.sum, magefile.go
/kind cleanup
/area dependency
- go.mod: Update github.com/uwu-tools/magex to v0.10.0
related to https://github.com/kubernetes-sigs/release-utils/pull/78
/assign @justaugustus  @saschagrunert @puerco  
cc: @kubernetes-sigs/release-engineering 
None
```release-note
- go.mod: Update github.com/uwu-tools/magex to v0.10.0
```
=> go.mod: Use uwu-tools/magex

.golangci.yml, git/git.go, github/record.go, github/replay.go, magefile.go, object/gcs.go
/kind cleanup
- bump golangci-lint to v1.52.2
/assign @saschagrunert @puerco @xmudrii 
None
```release-note
NONE
```
=> bump golangci-lint to v1.52.2

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum
/kind cleanup
- upgrade go-github to v53
/assign @palnabarun @Verolop @saschagrunert 
None
```release-note
upgrade go-github to v53
```
=> upgrade go-github to v53

git/git.go
/kind feature
- add ConfigureGlobalCustomUserAndEmail function
/assign @saschagrunert @puerco @xmudrii 
None
```release-note
add ConfigureGlobalCustomUserAndEmail function
```
=> add ConfigureGlobalCustomUserAndEmail function

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum, object/objectfakes/fake_store.go
/kind feature
- upgrade to go-github v58
- add pull request reviewers function
/assign @xmudrii @saschagrunert @puerco @Verolop   
None
```release-note
- upgrade to go-github v58
- add pull request reviewers function
```
=> Add pull request reviewers function

github/github.go
/kind feature
- add retry to create pull request
i am running this function in some automation that i have and sometimes i got a rate limit, and the PR creation fails, adding a wait for the rate limit for the create PR
/assign @xmudrii @puerco @Verolop 
None
```release-note
add retry to create pull request function
```
=> add retry to create pull request function

.github/workflows/e2e.yml
/kind cleanup
- run only on kubernetes-sigs/release-sdk repo
/assign @saschagrunert @Verolop @xmudrii 
None
```release-note
run only on kubernetes-sigs/release-sdk repo
```
=> run only on kubernetes-sigs/release-sdk repo

.golangci.yml, gcli/gcli.go, git/describe.go, git/git.go, git/git_test.go, github/fork.go, github/github.go, github/github_test.go, github/record.go, github/replay.go, github/replay_test.go, object/gcs.go, object/gcs_test.go, obs/error.go, obs/packages.go, obs/project.go, osc/config.go, osc/osc.go, osc/osc_test.go, regex/regex.go, sign/impl.go, sign/options.go, sign/sign.go, sign/sign_test.go, test/integration/container_registry.go, test/integration/git_test.go, test/integration/sign_test.go
/kind cleanup
Enable a bunch of auto fixing linters and apply a new config.
None
None
```release-note
None
```
=> Update golangci-lint and fix lints

test/integration/git_test.go
/kind bug
- fix TestCommitSuccess test
Fixes https://github.com/kubernetes-sigs/release-sdk/issues/406
```release-note
fix TestCommitSuccess test
```
=> fix TestCommitSuccess test

.golangci.yml, gcli/gcli.go, git/describe.go, git/git.go, git/git_test.go, github/fork.go, github/github.go, github/github_test.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum, object/gcs.go, obs/packages.go, obs/project.go, osc/osc.go, osc/osc_test.go, sign/impl.go, sign/options.go, sign/sign.go, sign/sign_test.go, test/integration/container_registry.go, test/integration/git_test.go, test/integration/sign_test.go
/kind cleanup
Update the linter configuration and fix the reports.
None
None
```release-note
None
```
=> Update golangci-lint config and fix reports

.golangci.yml, git/git.go, git/git_test.go, github/github_test.go, go.mod, go.sum, obs/project.go
/kind cleanup
Pin the latest release-utils and update golangci-lint.
None
None
```release-note
None
```
=> Switch to golangci-lint v2

github/github.go, github/github_test.go, github/githubfakes/fake_client.go, github/internal/retry.go, github/internal/retry_test.go, github/record.go, github/replay.go, go.mod, go.sum
/kind cleanup
- update go-github to v72
/assign @puerco @xmudrii @ameukam 
cc @kubernetes-sigs/release-actions-maintainers 
None
```release-note
update go-github to v72
```
=> update go-github to v72
