kubernetes-sigs/release-sdk

- .golangci.yml
- dependencies.yaml
- gcli/gcli.go
- git/git.go
- github/github.go
- github/record.go
- go.mod
- go.sum
- mage.go
- magefile.go
- object/gcs.go
- object/store.go
- regex/regex.go
- scripts/boilerplate/boilerplate.Dockerfile.txt
- scripts/boilerplate/boilerplate.Makefile.txt
- scripts/boilerplate/boilerplate.generatego.txt
- scripts/boilerplate/boilerplate.go.txt
- scripts/boilerplate/boilerplate.py.txt
- scripts/boilerplate/boilerplate.sh.txt
- scripts/verify-build.sh
(Follow-up from https://github.com/kubernetes/test-infra/pull/23585 to enable repo presubmits.)
- Init presubmits (from sigs.k8s.io/release-utils)
- generated: Run `go mod tidy`
- lint(gocritic/ifElseChain): rewrite if-else to switch statement
- golangci-lint: Enforce stricter lint settings
- lint(revive/if-return): redundant if ...; err != nil check
...just return error instead.
- lint(revive/exported): comment on exported Foo
...should be of the form "Foo ..."
> Init presubmits (from sigs.k8s.io/release-utils) 

- OWNERS
- OWNERS_ALIASES
This PR updates the OWNERS and OWNERS_ALIASES files
to update the approvers and reviewers if the repository
to match other SIG Release repos, namely:
* Updates the sig-release-leads alias to reflect current members
* Adds a release-engineering-approvers group including leads and release managers
* Adds a release-engineering-reviewers group with Release Manager Associates
/assign @justaugustus 
> OWNERS: Update to match the current SIG Release roles

- github/internal/retry.go
We should also check if the calculated wait duration is negative to never wait for such a value. In that case we always fallback to the default wait time for retry.
> Check for negative wait durations

- github/internal/retry.go
- github/internal/retry_test.go
This commit adds logic to the github call retrier to detect the GitHub
secondary rate limit. When detecting the limit, the github client
will wait for the set time (1 min) plus a few seconds more.
The idea behind this is that when doing calls in parallel we don't
want to set loose all workers to the API at the same time.
Permanent fix for https://github.com/kubernetes/release/pull/2324
Fixes https://github.com/kubernetes/release/issues/2225
Fixes https://github.com/kubernetes/release/issues/2302
/kind bug failing-test flake
/priority important-soon
/assign @justaugustus @Verolop @palnabarun @saschagrunert
/cc @kubernetes/release-engineering
/milestone v1.23
> github: Detect secondary rate limit

- LICENSE
Looks like this was missing in bootstrap.
/assign @saschagrunert @puerco @cpanato 
cc: @kubernetes-sigs/release-engineering 
/priority critical-urgent
> LICENSE: Init Apache 2.0 license

- github/fork.go
The ability to create forks was reused in `krel promote-images`,
which is now being moved into sigs.k8s.io/promo-tools as
`kpromo pr`: https://github.com/kubernetes-sigs/promo-tools/pull/458
Given the functionality has proven to be useful in multiple places,
we'll move it here so it can be leveraged for other tools.
/assign @puerco @xmudrii @Verolop 
cc: @kubernetes-sigs/release-engineering
> github: Add forking functionality from `krel release-notes`

- git/git.go
- git/git_integration_test.go
We've removed `anago`, so we should stop impersonating it in git 🙃 
/assign @puerco @Verolop 
cc: @kubernetes-sigs/release-engineering
> git: Rename default git user to `k8s-release-robot`

- github/github.go
- exposing the ListTags for a GitHub Repository to be able to fetch all tags
part of https://github.com/kubernetes-sigs/zeitgeist/issues/61
/assign @puerco @Verolop @xmudrii @palnabarun 
> add ListTags function

- git/git.go
- git/git_integration_test.go
We now add two API methods to the `git` package, which will be used for
the automatic fast forward of release branches.
Refers to https://github.com/kubernetes/release/issues/2386
> Add `LatestReleaseBranch()` and `RemoteBranches()` git API

- sign/sign.go
- sign/sign_test.go
Following up from https://github.com/kubernetes-sigs/release-sdk/pull/19.
Referencing discussion: https://github.com/kubernetes-sigs/release-sdk/pull/19#issuecomment-1016656791
> Split `Sign` API into `SignImage` and `SignFile`

- sign/sign.go
We should not expose the methods of that implementation to the end user
and therefore make it struct internal.
Refers to #21
> Make signer implementation internal

- sign/impl.go
- sign/options.go
- sign/sign.go
We should not block forever on the signing process if the network
flakes. This means we now use a default timeout of 3 minutes for each
signing invocation.
Follow-up on https://github.com/kubernetes-sigs/release-sdk/pull/25
Refers to https://github.com/kubernetes-sigs/release-sdk/issues/21
> Add signing timeout

- sign/impl.go
- sign/sign.go
- sign/sign_test.go
- sign/signfakes/fake_impl.go
We now test for issues on `os.SetEnv` as well as adding test around
those cases.
Follow-up on #25
Refers to #21
> Catch os.SetEnv errors

- sign/impl.go
- sign/sign.go
- sign/sign_test.go
- sign/signfakes/fake_impl.go
- Based on slack conversation here: https://kubernetes.slack.com/archives/C2C40FMNF/p1644342988804439?thread_ts=1644269088.802199&cid=C2C40FMNF 
- Keep in sync with https://github.com/kubernetes-sigs/release-sdk/pull/20
@palnabarun this may impact / need rebase for your #29
> Split `Verify` API into `VerifyImage` and `VerifyFile`

- git/git_test.go
- test/integration/git_test.go
We introduced the `IntegrationTest` target in #31 which is supposed to be used for running the integration tests. The Test target is supposed to be used for running the unit tests.
Therefore, this PR moves the Git integration from `Test` to `IntegrationTest` (and `pkg/integration`).
/assign @puerco @saschagrunert @cpanato 
> Move Git integration tests to the test/integration pkg

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
This PR adds the standard pull request template we use across sig release repos to this repository.
I'm sneaking two entries into the repo .gitignore (the .vscode and tmp/ dirs)
/cc @kubernetes-sigs/release-engineering 
> Pull Request Template

- sign/impl.go
- sign/impl_test.go
- sign/sign.go
- sign/sign_test.go
- sign/signfakes/fake_impl.go
Thit PR introduces a new method to the signer object `IsImageSigned()` which returns a bool indicating if an image reference has signatures attached to it.
This is needed because we need to know if images are signed before triggering image verification on a reference.
Needed for verifying images in the container image promoter: https://github.com/kubernetes-sigs/promo-tools/pull/498
Related to
https://github.com/kubernetes/release/issues/2383
https://github.com/kubernetes/release/issues/2227
/cc @saschagrunert @cpanato @xmudrii @PushkarJ @palnabarun   
```release-note
New signer method `IsImageSigned()` allows tp check if an image reference has one or more digital signatures attached.
```
> sign: IsImageSigned()

- sign/impl.go
- sign/impl_test.go
/kind bug
This PR fixes a bug in the IsSignedImage() function and also modifies the IsImageSignedInternal function to use the OCI remote package in cosign to check for signatures. This means that the implementation now uses a more primitive API saving a layer of abstraction on top of it.
None
/cc @saschagrunert @cpanato @xmudrii @PushkarJ @palnabarun
```release-note
Fixed a bug when checking if images are signed and by the way switched the signer implementation to use the OCI remote package from cosign.
```
> sign: Use cosign's OCI Remote to check for signatures

- sign/impl.go
- sign/impl_test.go
- sign/options.go
- sign/sign.go
- sign/sign_test.go
- sign/signfakes/fake_impl.go
/kind bug
/kind feature
This PR does two things:
First, it enables setting an identity token in the signer options enable doing keyless signing in environments that are not supported in the cosign identity providers (compute engine/GCP, github, spiffe or fixed file). The identity token can be defined in a new setting called `Options.IdentityToken`.
Secondly, since we are importing the cosign CLI, we need to ensure we have an OIDC identity token before attempting to do keyless signing. The reason is that we need to fail early if we don't have one or else the cosign CLI will attempt to ask the user  for one non interactively and fail,  as it will never get it:
```
Enter the verification code XXXX-XXXX in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=XXX-XXXX
```
This PR …
> Signer: Support external OIDC tokens. Fail early if token missing.

- sign/impl.go
- sign/impl_test.go
- sign/options.go
- sign/sign.go
- sign/signfakes/fake_impl.go
/kind cleanup
We now feature a custom logger within the `Options` structure and remove
the logger from the `defaultImpl` by passing it around.
We also add a convenience method to the options to create a context
based on the internally provided timeout.
None
None
```release-note
Added `Logger` to sign options. By default we initialize a new logger if `nil`.
```
> Remove log from signer impl and add it to options

- sign/options.go
- sign/sign.go
/kind feature
This commit introduces an option to control if signatures get
attached to images after signing. It may be the case that we
need to store the signature or attach it at a different time.
Part of https://github.com/kubernetes/release/issues/2383
Most likely we will have to attach the signatures in the image promoter outside of cosign
as one identity signs and another promotes. So we need to make attaching it from the
signer optional to avoid an error when the signer is not authorized to push.
/assign @cpanato @saschagrunert
/cc @kubernetes-sigs/release-engineering 
```release-note
When signing a container image, attaching the signature by pushing it to the registry is now optional. 
```
> Make attaching image signature optional

- sign/sign.go
/kind bug
When signing an image without attaching the signature, do not attempt
to verify the remote reference as it will always fail.
None
Returned `SignedObject` is still empty waiting for https://github.com/kubernetes-sigs/release-sdk/issues/37
/cc @kubernetes-sigs/release-engineering 
```release-note
Fixed a bug where image signing "failed" when trying to verify signed images that do not have their signatures attached
```
> Dont verify remote image when not attaching

- sign/sign.go
- sign/sign_test.go
/kind bug
Skips image verification if there are no matching signatures
None
None
```release-note
Skips image verification if there are no matching signatures
```
/assign @puerco 
/cc @kubernetes-sigs/release-engineering
> sign: skip image verification if no signature is present

- sign/sign.go
/kind cleanup
To increase the verbosity we now log an info message if an unsigned images is skipped during its verification.
None
None
```release-note
Logging an info message if an unsigned images is skipped during its verification.
```
> Log on unsigned image verification

- internal/tools.go
- mage.go
- sign/impl.go
- sign/sign.go
- sign/signfakes/fake_impl.go
POC Implementation of file signing using cosign
fixes #22 
Notes:
1. `SignedObject` doesn't contain the fields to store the signature or the signature path yet.
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
> Implement file signing

- gcli/gcli.go
- git/describe.go
- git/git.go
- git/git_test.go
- github/fork.go
- github/github.go
- github/record.go
- go.mod
- object/gcs.go
- sign/impl.go
- sign/sign.go
/kind cleanup
This removes the direct `github.com/pkg/errors` dependency while using the native golang error wrapping.
None
None
```release-note
Removed direct `github.com/pkg/errors` dependency by using golang native error wrapping.
```
> Switch to golang native error wrapping

- go.mod
- sign/options.go
- sign/sign.go
/kind bug
This commit adds retries to the signing package. When signing an image, we will now retry and wait to account for eventual consistency in the registry.
Fixes https://github.com/kubernetes-sigs/promo-tools/issues/536
/assign @cpanato @justaugustus 
/cc @kubernetes-sigs/release-engineering 
```release-note
The signer object will now wait and retry if validating a signature fails after signing. The number of retries can be controlled with a new `MaxRetries` option.
```
> Retry verification if it fails after signing

- github/replay.go
- github/replay_test.go
- github/testdata/ListTags-0.json
/kind bug
Fixes bug on GitHub replayer to return recorded data instead of empty slice.
Fixes #59 
```release-note
GitHub replay `ListTags` to return data instead of empty slice.
```
> GitHub replay `ListTags` to return data instead of empty slice

- github/github.go
- go.mod
- go.sum
/kind feature
This reduces GitHub rate-limit quota usage when doing repetitive task, such as:
- running tests in development
- release notes workflow of generating both markdown and JSON in the same sitting, which calls identical requests in both process.
Fixes #57
```release-note
GitHub API responses are now automatically cached, preventing getting rate-limited by GitHub in repetitive usage.
```
> Add use httpcache to cache GitHub responses

- github/github.go
- go.mod
- go.sum
/kind bug
The httpcache transport is breaking authentication where no fix seems to
be implemented yet. I'd propose to revert the change for now to be able
to use authenticated requests in tools like
`k/release/cmd/release-notes`.
Refers to: https://github.com/google/go-github/issues/1503, https://github.com/gregjones/httpcache/pull/104
None
Reverts https://github.com/kubernetes-sigs/release-sdk/pull/58
```release-note
Fixed broken authorization caused by httpcache.
```
> Revert httpcache integration

- github/fork.go
/kind bug
Fixing the nil error to be printed to the user.
None
None
```release-note
Fixed invalid error message if branch already exists in GitHub fork.
```
> Fix error message if branch already exists in fork

- sign/options.go
- test/integration/sign_test.go
/kind cleanup
This resolves two outstanding TODO's, because we can now pass `nil` to
`cosign.GenerateKeyPair`. Beside that, we also use `nil` as default
PassFunc, because this will be handled in the same way as providing no
password at all.
None
```release-note
Changed default sign `Options.PassFunc` to be `nil`, which acts as having no password provided at all.
```
> Pass `nil` on integration test key generation

- .github/dependabot.yml
- .github/workflows/e2e.yml
- dependencies.yaml
- magefile.go
- sign/object.go
- sign/sign.go
- sign/sign_test.go
- test/e2e/sign_test.go
/kind api-change
We now add support for running e2e tests via GitHub actions.
Beside that, we also add accessor methods for `Image()` and `File()` of `SignedObject` to keep the API separated.
None
Last CI run in my fork: https://github.com/saschagrunert/release-sdk/runs/7407613686
```release-note
Added accessor methods for `Image()` and `File()` of `SignedObject`.
```
> Add support for GitHub actions e2e tests

- .github/workflows/e2e.yml
/kind bug
follow up of https://github.com/kubernetes-sigs/release-sdk/pull/91 
the Identity token is not inject when the PR come from a fork. to we inject that we need to use the `pull_request_target` but that might generate possible security issues.
However this repository does not have any secrets or sensitive data, but the attacker can use the token for other things.
So removing the `pull_request` target for now.
/assign @ameukam @saschagrunert @puerco @jeremyrickard @palnabarun  
```release-note
NONE
```
> remove pull_request target that does not work with fork prs

- .golangci.yml
- go.mod
- go.sum
- sign/impl.go
- sign/options.go
- sign/sign.go
- sign/sign_test.go
- sign/signfakes/fake_impl.go
- test/integration/sign_test.go
/kind feature
We now expose a new, highly parallel image signature verification API. This allows us to re-use built transports and efficiently looking up the signatures of the images.
Refers to https://github.com/kubernetes-sigs/promo-tools/issues/637
```release-note
Added `ImagesSigned` API
```
> Add `ImagesSigned` API

- go.mod
- go.sum
- sign/impl.go
- sign/options.go
- sign/sign.go
- sign/sign_test.go
- sign/signfakes/fake_impl.go
- test/integration/sign_test.go
/kind feature
We now cache the results during signature retrieval and re-use them accordingly. We also implement a new `VerifyImages` API for batch processing.
Fixes https://github.com/kubernetes-sigs/release-sdk/issues/124
Refers to https://github.com/kubernetes-sigs/promo-tools/issues/637
None
```release-note
Added caching and `VerifyImages` API
```
> Add caching and `VerifyImages` API

- git/git.go
/kind bug
- block commands that can run malicious injection
/assign @saschagrunert @xmudrii @Verolop 
None
```release-note
NONE
```
> block commands that can run malicious injection

- git/git.go
/kind feature
I need both variables in k/release for some additional checks if a commit is from the bot a human.
Refers to https://github.com/kubernetes/release/issues/2807
None
```release-note
Updated `git.DefaultGitUser` and `git.DefaultGitEmail` to be public constants.
```
> Make `git.DefaultGitUser` and `git.DefaultGitEmail` public

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/record.go
- github/replay.go
/kind feature
We now have a way to list issues for GitHub repositories. 
Refers to https://github.com/kubernetes/release/issues/2807
None
```release-note
Added `github.ListIssues` API.
```
> Add `ListIssues` GitHub API

- git/git.go
/kind bug
/kind regression
Fixing the broken method by removing the `--tags` arg.
None
A regression from https://github.com/kubernetes-sigs/release-sdk/pull/136
```release-note
Fixed `RemoteTags()` method
```
> Fix `RemoteTags()` method

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/internal/retry.go
- github/internal/retry_test.go
- github/record.go
- github/replay.go
- go.mod
- go.sum
/kind cleanup
I noticed while trying to leverage this package downstream (https://github.com/uwu-tools/gh-jira-issue-sync/issues/57, https://github.com/uwu-tools/gh-jira-issue-sync/pull/58) that I had to downgrade the tool's go-github version.
Let's update the go-github dep to https://github.com/google/go-github/releases/tag/v48.2.0, which also happens be their first release to support GitHub's new calendar-based API versions (https://github.com/google/go-github/pull/2581, https://github.com/google/go-github/issues/2580, https://github.blog/2022-11-28-to-infinity-and-beyond-enabling-the-future-of-githubs-rest-api-with-api-versioning/)
/assign @saschagrunert @Verolop @puerco @cpanato 
```release-note
```
> go.mod: Update `github.com/google/go-github` to v48.2.0

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/record.go
- github/replay.go
/kind feature
github: Add `ListComments` method
More stuff I need for https://github.com/uwu-tools/gh-jira-issue-sync/issues/57. 😛 
(Follow-up to https://github.com/kubernetes-sigs/release-sdk/pull/147.)
/assign @Verolop @puerco @cpanato @xmudrii 
```release-note
github: Add `ListComments` method
```
> github: Add `ListComments` method

- regex/regex.go
/kind feature
Every method using the `BranchRegex` will fail if the default branch is `main`, which is a valid release branch considering it has been renamed from `master`.
None
None
```release-note
Allow `main` to be a valid release branch for `regex.BranchRegex` (used via `git.IsReleaseBranch(string)`).
```
> Allow `main` to be a release branch

- test/integration/sign_test.go
**What type of PR is this?**
> /kind cleanup
**What this PR does / why we need it**:
This PR updates the registry from k8s.gcr.io to registry.k8s.io
**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/k8s.io/issues/4738
> Update registry k8s.gcr.io -> registry.k8s.io

- sign/options.go
- sign/sign.go
/kind feature
This allows signing multi-arch images together with their discrete entities.
None
PTAL @kubernetes-sigs/release-engineering 
```release-note
Added `Recursive` option to sign package to be able to sign multi-arch images containing their discrete images.
```
> Add `sign.Options.Recursive` config

- sign/sign.go
/kind regression
Images signed with krel are failing verification. This can be observed in build-master job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build/1661016905332297728
```
level=fatal msg="failed to run: push container images: publish container images: get manifest images: traversing path: executing tarball callback: sign container image: retrying image verification: timed out waiting for the condition"
```
I tried running following two commands locally:
```
cosign verify gcr.io/k8s-staging-ci-images/conformance-amd64:v1.28.0-alpha.0.1136_61d455ed1173cd --certificate-identity=prow-build@k8s-infra-prow-build.iam.gserviceaccount.com --certificate-oidc-issuer=https://accounts.google.com
cosign verify …
```
> Upload signatures to transparency log

- sign/options.go
- test/integration/sign_test.go
/kind feature
- Default CertIdentityRegexp to `(prow-build@k8s-infra-prow-build.iam.gserviceaccount.com)|((krel-trust|krel-staging)@k8s-releng-prod.iam.gserviceaccount.com)` in default signer options
- Default CertOidcIssuer to `https://accounts.google.com/` in default signer options
Those two options/flags are required now that we use cosign v2. Identity should always be the same, and issue should match all identities that we use currently.
None
```release-note
- Default CertIdentityRegexp to `(prow-build@k8s-infra-prow-build.iam.gserviceaccount.com)|((krel-trust|krel-staging)@k8s-releng-prod.iam.gserviceaccount.com)` in default signer options
- Default CertOidcIssuer to `https://accounts.google.com/` in default signer options
```
/assign @saschagrunert @cpanato 
cc …
> Default CertIdentityRegexp and CertOidcIssuer in SignOptions

- osc/auth.go
- osc/config.go
- osc/osc.go
/kind feature
This PR adds `osc` package for running the `osc` tool (OpenBuildService CLI). We'll eventually capture commands that we use and create functions for each command, but for now, this approach should be good enough.
```release-note
Add `osc` package for running OpenBuildService CLI
```
> Add osc package for running osc tool

- osc/osc.go
/kind cleanup
`osc` calls must be executed in the specific project or package directory. That said, let's make this explicit and make functions in the `osc` package take working directory.
```release-note
Change functions in `osc` package to take the working directory
```
/assign @saschagrunert @cpanato 
> Make osc functions take working directory

- sign/sign.go
/kind cleanup
This PR propagates the actual error back to caller when reference verification fails after timeout in exponentional backoffs  reattempts. Currently there is no way to figure out why the verification fails as only timeout error is returned back to the caller.
```release-note
NONE
```
> signing/reference-verification: propagating error to the caller

- .gitignore
- obs/project.go
Reference: [#2295](https://github.com/kubernetes/sig-release/issues/2295)
This PR is created with the purpose of adding the initial project structure for the OBS project meta file for golang library
> obs: add initial Project types

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/internal/retry.go
- github/internal/retry_test.go
- github/record.go
- github/replay.go
- go.mod
- go.sum
/kind cleanup
/kind feature
- update go-github to v55
/assign @saschagrunert @puerco @Verolop @xmudrii 
None
```release-note
update go-github to v55
```
> update go-github to v55

- obs/error.go
- obs/project.go
Reference: https://github.com/kubernetes/sig-release/issues/2295
- Add the library functions to interact with OBS.
> obs: add library functions - 01

- obs/project.go
Reference: https://github.com/kubernetes/sig-release/issues/2295
Add the library functions to interact with OBS.
> obs: add library functions - 02

- git/git.go
/kind feature
This PR adds `Shallow*` variants to our clone functions. These work exactly as their counterparts but perform a shallow (depth 1) clone of repositories to work with large repositories at HEAD more efficiently.
The new functions are:
- `git.ShallowCloneOrOpenRepo()`
- `git.ShallowCloneOrOpenGitHubRepo()`
- `git.ShallowCleanCloneGitHubRepo()`
Note that this PR has many lines but at its core, it is the same logic just broken into ever more specific utility functions to reuse our code. The outward-facing functions just invoke the internal ones with a different options set. Roughly:
```
CleanCloneGitHubRepo
|
CloneOrOpenRepo
\
cloneOrOpenRepo  --- cloneRepository   
/
ShallowCloneOrOpenRepo
|
ShallowCleanCloneGitHubRepo
```
None
/assign @saschagrunert @cpanato @xmudrii …
> Shallow clone variants

- github/github.go
- github/github_test.go
- go.mod
/kind feature
This PR adds another method to the GitHub client called `UpdateReleasePageWithOptions`. The idea is to move everything that is optional in a release into `UpdateReleasePageOptions`, so that the function signature no longer changes if other fields of a GitHub release need to be set. The field in question in this situation is `MakeLatest`, but I figured it makes sense to copy `NewIssue` behaviour, in case releases gain additional fields/opts in the future.
I am adding this so that `krel` can (once this is available) decide whether a release should be marked as latest or not. This is an issue tracked as https://github.com/kubernetes/kubernetes/issues/119472.
This came out a brief discussion at https://kubernetes.slack.com/archives/C2C40FMNF/p1702501467543419, I hope it …
> Add additional method to update GitHub releases with more flexible opts

- object/gcs.go
- object/gcs_test.go
- object/objectfakes/fake_store.go
- object/store.go
/kind bug
fast builds store the marker in `gs://k8s-release-dev/ci/latest-fast.txt` instead of `gs://k8s-release-dev/ci/fast/latest-fast.txt` which is problematic. Look at https://github.com/kubernetes/test-infra/pull/31486 for specific details
Part of https://github.com/kubernetes/release/issues/3403
```release-note
breaking change: fast marker (latest-fast.txt) is now stored inside the fast folder instead of the gcsRoot folder(ci)
```
> Publish the marker inside the fast folder

- git/git.go
- git/gitfakes/fake_repository.go
- github/fork.go
- test/integration/git_test.go
/kind feature
- add option to set ssh or http for preparefork
- add push with options for special cases you need to define better the push
None
```release-note
- add option to set ssh or http for preparefork
- add push with options for special cases you need to define better the push
```
> Update preparefork to accept ssh/http option and add new function to push with options

- git/git.go
- git/git_test.go
- github/fork.go
- test/integration/git_test.go
/kind feature
- add options to preparefork to when you need to configure special things
None
```release-note
add options to preparefork to when you need to configure special things
```
> add options to preparefork to when you need to configure special things

- git/git.go
- git/git_test.go
- github/fork.go
- test/integration/git_test.go
/kind feature
- add option to not update the repo
when we do a fresh close there is no need to update the repo, so adding a flag to say we dont want to update it
this function is getting bigger, i will refactor that to we pass options to reduce the signature
/assign @puerco @xmudrii 
None
```release-note
NONE
```
> add option to not update the repo

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/internal/retry.go
- github/internal/retry_test.go
- github/record.go
- github/replay.go
- go.mod
- go.sum
/kind cleanup
/kind feature
- update go-github to v60
/assign @puerco @saschagrunert @Verolop 
None
```release-note
update go-github to v60
```
> update go-github to v60

- .github/workflows/e2e.yml
- dependencies.yaml
- sign/sign.go
- test/e2e/sign_test.go
/kind bug
when calling `signer.IsImageSigned` in a image that is not signed it caches the result and if you sign the image after that it fails in the verify signature because that uses a cached info.
deleting any cache if that exists after a success signature will force the verify run the process again but this time with an image that was signed.
this test was failing for a looong time
green run: https://github.com/kubernetes-sigs/release-sdk/actions/runs/8522252234/job/23342048039
/assign @saschagrunert @puerco @xmudrii 
None
```release-note
fix e2e tests
```
> fix e2e tests

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/record.go
- github/replay.go
/kind feature
- add rate limit api check
if we need to check the rate limit of a GH token and pause or do anything else
/assign @puerco @saschagrunert @xmudrii 
None
```release-note
add GH rate limit api check
```
> add rate limit api check

- git/git.go
- git/git_test.go
/kind feature
- if GIT_COMMITTER_EMAIL/GIT_COMMITTER_NAME use that and not the git config info
related to https://github.com/kubernetes-sigs/promo-tools/issues/782
/assign @saschagrunert @puerco @xmudrii 
```release-note
if GIT_COMMITTER_EMAIL/GIT_COMMITTER_NAME use that and not the git config info
```
> if GIT_COMMITTER_EMAIL/GIT_COMMITTER_NAME use that and not the git config info

- git/git.go
- git/git_test.go
/kind feature
This will be helpful for the release notes tool to skip the `--start-rev` commit, which usually points to a previous tag.
None
None
```release-note
git: added API to retrieve `NextCommit`
```
> git: add API to retrieve `NextCommit`

- osc/osc.go
- osc/osc_test.go
/kind feature
Add the new API which is capable of failing on wait.
Refers to: https://github.com/kubernetes/release/issues/3632
None
```release-note
Added `osc` package API `Version` and `WaitResults`.
```
> Add `osc` API for `Version` and `WaitResults`

- .github/workflows/e2e.yml
- test/e2e/sign_test.go
Generates a test file from the GHA workflow that gets signed in the e2e test similar to image signing
/kind cleanup
Fix #93
Since the test suite uses keyless signing, I haven't fully tested the patch using the existing workflow.
There's a few options that I can think of:
- Run e2e also on PRs (preferred) 
- Mirror the repo to duplicate the workflow and testing setup
NONE
> Add e2e test for file signing

- .github/workflows/e2e.yml
- .golangci.yml
- dependencies.yaml
- git/git_test.go
- go.mod
- go.sum
/kind cleanup
Use go 1.23 to build this project.
None
None
```release-note
None
```
> Switch to go 1.23

- test/integration/git_test.go
/kind cleanup
follow up of https://github.com/kubernetes-sigs/release-sdk/pull/407#pullrequestreview-2539708854
None
```release-note
NONE
```
> update TestCommitSuccess test

- github/github.go
- github/github_test.go
- github/githubfakes/fake_client.go
- github/record.go
- github/replay.go
/kind api-change
Add the flag Draft to expose the same attributes as in the NewPullRequest (github.com/google/go-github/v60/github). Happy to create a new function if we feel this is gonna break many things.
```release-note
Add a flag draft to the function call CreatePullRequest(...)
```
> CreatePullRequest: add Draft flag to func args
